# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
dist: trusty
os:
  - linux
  - osx
julia:
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

before_install:
  - julia -e 'using Pkg; Pkg.pkg"add https://github.com/xtyangpsp/SeisConvert.jl.git
      https://github.com/kura-okubo/SeisDownload.jl.git
      https://github.com/jaredbryan881/SeisXcorrelation.jl.git
      https://github.com/kura-okubo/SeisRemoveEQ.jl.git
      https://github.com/kura-okubo/SeisBeamforming.git"';
  - julia -e 'using Pkg; Pkg.pkg"add Test"';

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  include:
    - stage: Documentation
      julia: 1.1
      script:

        - julia --project=docs/ -e 'using Pkg;
                    Pkg.pkg"add https://github.com/xtyangpsp/SeisConvert.jl.git https://github.com/kura-okubo/SeisDownload.jl.git https://github.com/jaredbryan881/SeisXcorrelation.jl.git https://github.com/kura-okubo/SeisRemoveEQ.jl.git https://github.com/kura-okubo/SeisBeamforming.git";
                    Pkg.develop(PackageSpec(path=pwd()));
                    Pkg.instantiate();
                    Pkg.build("NoiseJul")'

        - julia -e 'using Pkg; Pkg.pkg"add https://github.com/xtyangpsp/SeisConvert.jl.git https://github.com/kura-okubo/SeisDownload.jl.git https://github.com/jaredbryan881/SeisXcorrelation.jl.git https://github.com/kura-okubo/SeisRemoveEQ.jl.git https://github.com/kura-okubo/SeisBeamforming.git";
                cd(Pkg.dir("NoiseJul")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'

      after_success: skip
