name = "NoiseJul"
uuid = "0423bd86-b6d2-11e9-05d5-e96651daa1f8"
authors = ["NoiseJul"]
version = "1.0.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
